const dummyReviewData = {
  date: "2024-11-30",
  breakfast: [
    {
      mealId: "1",
      mealName: "Pancakes",
      qualityRatings: {
        totalMembers: 200,
        totalRating: 4.2,
        fiveStarRating: 100,
        fourStarRating: 50,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
      tasteRatings: {
        totalMembers: 200,
        totalRating: 4.7,
        fiveStarRating: 90,
        fourStarRating: 60,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
    },
    {
      mealId: "2",
      mealName: "Scrambled Eggs",
      qualityRatings: {
        totalMembers: 200,
        totalRating: 4.6,
        fiveStarRating: 100,
        fourStarRating: 50,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
      tasteRatings: {
        totalMembers: 200,
        totalRating: 4.7,
        fiveStarRating: 90,
        fourStarRating: 60,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
    },
    {
      mealId: "3",
      mealName: "Toast with Butter",
      qualityRatings: {
        totalMembers: 200,
        totalRating: 4.5,
        fiveStarRating: 100,
        fourStarRating: 50,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
      tasteRatings: {
        totalMembers: 200,
        totalRating: 4.4,
        fiveStarRating: 90,
        fourStarRating: 60,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
    },
    {
      mealId: "4",
      mealName: "Fruit Salad",
      qualityRatings: {
        totalMembers: 200,
        totalRating: 4.7,
        fiveStarRating: 100,
        fourStarRating: 50,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
      tasteRatings: {
        totalMembers: 200,
        totalRating: 4.7,
        fiveStarRating: 90,
        fourStarRating: 60,
        threeStarRating: 30,
        twoStarRating: 15,
        oneStarRating: 5,
      },
    },
  ],
  lunch: [
    {
      mealId: "2",
      mealName: "Grilled Chicken",
      qualityRatings: {
        totalMembers: 200,
        fiveStarRating: 110,
        fourStarRating: 60,
        totalRating: 4.3,
        threeStarRating: 20,
        twoStarRating: 5,
        oneStarRating: 5,
      },
      tasteRatings: {
        totalMembers: 200,
        totalRating: 4.5,
        fiveStarRating: 95,
        fourStarRating: 70,
        threeStarRating: 20,
        twoStarRating: 10,
        oneStarRating: 5,
      },
    },
  ],
  dinner: [
    {
      mealId: "3",
      mealName: "Spaghetti Bolognese",
      qualityRatings: {
        totalMembers: 200,
        totalRating: 4.8,
        fiveStarRating: 120,
        fourStarRating: 50,
        threeStarRating: 20,
        twoStarRating: 5,
        oneStarRating: 5,
      },
      tasteRatings: {
        totalMembers: 200,
        fiveStarRating: 100,
        totalRating: 4.4,
        fourStarRating: 60,
        threeStarRating: 25,
        twoStarRating: 10,
        oneStarRating: 5,
      },
    },
  ],
};

export default dummyReviewData;
